version: '3'

#services:
  app:
    build: .
    ports:
        - 8000:8000
    volumes:
    - '.:/django-sample'
    - './gunicorn:/etc/systemd/system/'
    
    tty: True
    stdin_open:  True
    depends_on:
        - db
    links: 
        - db
    
  db:
    image: postgres:11
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - './gunicorn:/etc/systemd/system/'
