version: '3'

services:

  web:
    build: .
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - '.:/django-sample'
    expose:
      - 8000
    tty: True
    stdin_open:  True
    depends_on:
        - db
    links: 
        - db
    
  db:
    image: postgres:11
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    tty: True

  nginx:
        build: ./nginx
        ports:
            - 1337:80
        tty: True
        volumes:
            - static_volume:/usr/src/app/staticfiles
        depends_on:
            - web

volumes:
  static_volume:
