# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    services:
      options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        
    - name: dokcer run
      shell: bash
      run: |
        docker-compose up -d
        
    - name:  Test
      shell: bash
      run: |
        docker-compose up -d
        docker-compose exec -T web bash
        pipenv install --system
        python manage.py migrate
        gunicorn --bind 0.0.0.0:8000 TodoProject.wsgi:application
        python manage.py test
