# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    # Job name is Greeting
    name: verify
    # This job runs on Linux
    runs-on: ubuntu-latest
    container: python:3.7
    services:
      postgres:
        image: postgres:11.2
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    steps:
    - uses: actions/checkout@v2 
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        
    - name:  Test
      shell: bash
      run: |
        docker-compose up -d
        docker-compose exec -T web bash
        pipenv install --system
        python manage.py migrate
        gunicorn --bind 0.0.0.0:8000 TodoProject.wsgi:application
        python manage.py test
